<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKUNBTdv\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKUNBTdv/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKUNBTdv.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKUNBTdv\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerKUNBTdv\App_KernelDevDebugContainer([
    'container.build_hash' => 'KUNBTdv',
    'container.build_id' => '6f56abba',
    'container.build_time' => 1734524464,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKUNBTdv');
